### ISSUE TITLE
[TASK] Acceptance Test of Stories - Sprint 2

### ISSUE THREAD

**Issue by taj-ch** [kpamela/StudyRing#124]
This issue is related to task #108 
Stories related to this sprint:
- [x] #42 [Story] Account access and information 
- [x] #48 [Story] User Dashboard 
- [x] #34 [Story] Creating a group 

Story points: 5
Hours: 3

**Comment by Zackkogan** [comment]
converted comment to checklist

**Comment by kpamela** [comment]
Nice and clear

**Comment by kpamela** [comment]
under testing

**Comment by kpamela** [comment]
![image](https://cloud.githubusercontent.com/assets/24784649/25017660/9e46d7f6-2052-11e7-97ac-3a5bd41c6429.png)

**Comment by taj-ch** [comment]
![34-1](https://cloud.githubusercontent.com/assets/14812605/25017683/adb04704-2052-11e7-8565-850d5128687b.png)
